on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Testing'
        run: pwd
        
      - name: 'Testing print'
        run: echo Ahmed


