on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3 

      - name: "loogin to docker"
        run: docker login --username mohamedamr1510 --password dckr_pat_E7kOTKQDjEUZF8hpQ3N7qIWpx6c



        



